name: Experiment 
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest
    permissions: 
        id-token: write
        packages: write
        contents: read
        attestations: write

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    #   - name: Docker Login
    #     uses: azure/docker-login@v2
    #     with:
    #       login-server: ${{ secrets.ACR_URL }}
    #       username: ${{ secrets.ACR_USERNAME }}
    #       password: ${{ secrets.ACR_PASSWORD }}

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password:  ${{ secrets.ACR_PASSWORD }}


      - name: Build and Push to ACR
        id: push
        uses: docker/build-push-action@v6.3.0
        with:
          push: true
          tags: ${{ secrets.ACR_URL }}/isks/test:latest
          file: ./src/Dockerfile
  
      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: ${{ secrets.ACR_URL }}/isks/test
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true  

